;; Original development-only constructor interfaces; no collection algorithms.
(deftype LiteralVector [meta cnt shift root tail __hash])
(deftype LiteralMap [meta cnt arr __hash])
(deftype LiteralHashMap [keys vals])
(deftype LiteralSet [meta hash_map __hash])
(set! (.-EMPTY_NODE LiteralVector) 17)
(set! (.-EMPTY LiteralVector) (LiteralVector. nil 0 5 17 (array) nil))
(set! (.-fromArray LiteralVector)
  (fn [xs no-clone] (LiteralVector. nil (alength xs) 5 no-clone xs nil)))
(set! (.-EMPTY LiteralMap) (LiteralMap. nil 0 (array) nil))
(set! (.-createAsIfByAssoc LiteralMap)
  (fn [xs] (LiteralMap. 1 (/ (alength xs) 2) xs nil)))
(set! (.-fromArrays LiteralHashMap)
  (fn [keys vals] (LiteralHashMap. keys vals)))
(set! (.-EMPTY LiteralSet) (LiteralSet. nil (LiteralMap. nil 0 (array) nil) nil))
(set! (.-createAsIfByAssoc LiteralSet)
  (fn [xs] (LiteralSet. 1 xs nil)))
