(ns suss-oracle.analysis-tag-runner
  (:require-macros [suss-oracle.analysis-tags :refer [observe]]))

(def scalar 7)
(def fixed (fn [x] x))
(def numeric (fn [] (+ "a" 1)))
(def ^:dynamic *dynamic* 8)
(def results
  [(observe "nil" nil)
   (observe "boolean" false)
   (observe "number" 42)
   (observe "string" "hello")
   (observe "keyword" :word)
   (observe "quoted-symbol" 'word)
   (observe "vector" [1 2])
   (observe "map" {:a 1})
   (observe "set" #{1 2})
   (observe "quoted-list" '(1 2))
   (observe "empty-list" '())
   (observe "arithmetic-string-storage" (+ "a" 1))
   (observe "do" (do 1 "last"))
   (observe "let" (let [x 7] x))
   (observe "loop" (loop [x 7] x))
   (observe "if-constant-true" (if true 1 "s"))
   (observe "if-constant-false" (if false 1 "s"))
   (observe "if-unknown-union" (if *dynamic* 1 "s"))
   (observe "if-unknown-same" (if *dynamic* 1 2))
   (observe "try-body" (try 1 (catch :default problem "caught")))
   (observe "var-number" scalar)
   (observe "var-function" fixed)
   (observe "dynamic-number" *dynamic*)
   (observe "invoke-unknown-return" (fixed 9))
   (observe "invoke-inferred-number-with-string-storage" (numeric))
   (observe "fn-number" (fn [] 42))
   (observe "fn-unknown" (fn [x] x))
   (observe "fn-parameter-hint" (fn [^number x] x))
   (observe "fn-mixed-methods" (fn ([] 1) ([x] "s")))
   (let [x 1] (observe "local-number" x))
   (let [^string x 1] (observe "local-hint" x))
   (let [x *dynamic*] (observe "local-any" x))])

(defn -main []
  ;; Execute every initializer and invoke observed functions separately. Encode
  ;; only scalar projections, leaving type/inference facts in the compiler log.
  (println (.stringify js/JSON
    #js [(count results) (nth results 11) (nth results 24)
         ((nth results 25)) ((nth results 26) 10)
         ((nth results 27) 11) ((nth results 28))
         ((nth results 28) 12) (nth results 29) (nth results 30)
         (nth results 31)])))
(set! *main-cli-fn* -main)
