(ns suss-oracle.context-facts
  (:require-macros [suss-oracle.context-macros :refer [context]]))
(context "top")
(def direct (context "def"))
(def doone (do (context "do-one")))
(def domany (do 0 (context "do-many")))
(def letone (let [x 1] (context "let-body")))
(def letinit (let [x (context "let-init")] x))
(def branch (if true (context "if-yes") (context "if-no")))
(def bare (try (context "bare-try")))
(def tried (try (context "try-body") (catch :default e (context "catch-body")) (finally (context "cleanup"))))
(def function ((fn [] (context "fn-body"))))
(def fnbranch ((fn [] (if true (context "fn-if-yes") (context "fn-if-no")))))
(do (context "do-stmt-one") (context "do-stmt-two"))
(defn -main [] (println (.stringify js/JSON (clj->js [direct doone domany letone letinit branch bare tried function fnbranch]))))
(set! *main-cli-fn* -main)
