(ns suss-oracle.function-scope-facts
  (:require-macros [suss-oracle.function-scope-macros :refer [scope]]))
(def hinted (fn [] (scope "hinted")))
(def named (fn n [] (scope "named")))
(def anonymous ((fn [] (scope "anonymous"))))
(def nested (fn outer [] ((fn inner [] (scope "nested")))))
(def inherited (fn outer [] ((fn [] (scope "inherited")))))
(def declared (fn* [] (scope "declared")))
(def shadowed (let [n 99] (fn n [] (scope "shadowed"))))
(def multiple (fn m ([] (scope "zero")) ([x] (scope "one"))))
(def variadic (fn v [& xs] (scope "rest")))
(scope "outside")
(defn -main [] (println (.stringify js/JSON (clj->js [(hinted) (named) anonymous (nested) (inherited) (declared) (shadowed) (multiple) (multiple 1) (variadic 1 2)]))))
(set! *main-cli-fn* -main)
