(ns suss-oracle.protocol-reload)
(defprotocol ReloadProbe (-reload-probe [this]))
(deftype ReloadValue [] ReloadProbe (-reload-probe [this] 17))
(def saved-protocol ReloadProbe)
(def saved-method -reload-probe)
(def saved-value (ReloadValue.))
(defprotocol ReloadProbe (-reload-probe [this]))
(defn -main [] (println (.stringify js/JSON #js [(identical? ReloadProbe saved-protocol) (implements? ReloadProbe saved-value) (implements? saved-protocol saved-value) (-reload-probe saved-value) (saved-method saved-value)])))
(set! *main-cli-fn* -main)
