(ns suss-oracle.publication-cells)
(def unbound)
(def nil-value nil)
(def false-value false)
(def zero-value 0)
(def undefined-value (aget #js [] 0))
(def effects (atom 0))
(def object-value #js {:valueOf (fn [] (reset! effects 99))})
(def ^:dynamic dynamic-value nil)
(defn -main []
  (let [values [(exists? unbound)
                (exists? nil-value)
                (exists? false-value)
                (exists? zero-value)
                (exists? undefined-value)
                (exists? object-value)
                (binding [dynamic-value undefined-value] (exists? dynamic-value))
                (exists? dynamic-value)
                @effects]]
    (.log js/console (.stringify js/JSON (clj->js values)))))
(set! *main-cli-fn* -main)
