#!/usr/bin/env python3
"""Generate reader name facts from pinned source, without claiming execution."""
import argparse
import hashlib
import json
from pathlib import Path

from cljs_inventory import PIN, ROOT, SOURCES, Scanner, bare, declarations, inventory_records

OUTPUT = ROOT / 'crates/suss-compile/src/portable/syntax_quote/core_names.rs'


def names_from_source(source, phase):
    names = set()
    for top in Scanner(source).all():
        for kind, name, form, _ in declarations(top):
            # Macro helper functions are JVM implementation details; only macro
            # declarations belong to the cljs.core macro resolution catalog.
            if phase == 'macro' and kind not in ('defmacro', 'defmacro-'):
                continue
            names.add(name)
            if kind == 'defprotocol':
                for method in form.children[2:]:
                    if method.kind != 'list':
                        continue
                    name_form = bare(method.children[0])
                    if name_form.kind != 'atom':
                        raise ValueError('invalid protocol method name')
                    names.add(name_form.text)
            elif kind in ('deftype', 'defrecord'):
                names.add('->' + name)
                if kind == 'defrecord':
                    names.add('map->' + name)
    return names


def generate():
    inventory_records()  # Enforce the pin and clean source before generation.
    names = set()
    provenance = []
    for relative in SOURCES:
        raw = (ROOT / 'clojurescript' / relative).read_bytes()
        phase = 'runtime' if relative.endswith('.cljs') else 'macro'
        names.update(names_from_source(raw.decode(), phase))
        provenance.append('// ' + relative + ' SHA256 ' + hashlib.sha256(raw).hexdigest())
    return '\n'.join([
        '// Generated by scripts/reader_core_catalog.py. Namespace facts only;',
        '// membership does not establish source loading or implementation.',
        '// Pinned ClojureScript ' + PIN + '.',
        *provenance,
        'pub(super) static CORE_READER_NAMES: &[&str] = &[',
        *('    ' + json.dumps(name, ensure_ascii=False) + ',' for name in sorted(names)),
        '];', '',
    ])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit('reader core catalog is stale or missing')
        print('reader core namespace catalog verified')
    else:
        OUTPUT.write_text(generated)
        print('reader core namespace catalog generated')


if __name__ == '__main__':
    main()
