//! Original typed language handler invocation, preserving exact payloads/cleanup.
use super::*;
pub(super) fn functions(b: &mut Builder, invoke: u32) {
    use Instruction::*;
    // Parameters body/handler/cleanup. Locals result/payload/pending/empty args.
    let body = vec![
        I32Const(0),
        ArrayNewDefault(ARGS),
        LocalSet(6),
        Block(BlockType::Empty),
        Block(BlockType::Result(VALUE)),
        TryTable(
            BlockType::Empty,
            Cow::Owned(vec![wasm_encoder::Catch::One { tag: 0, label: 0 }]),
        ),
        Block(BlockType::Empty),
        Block(BlockType::Result(VALUE)),
        TryTable(
            BlockType::Empty,
            Cow::Owned(vec![wasm_encoder::Catch::One { tag: 0, label: 0 }]),
        ),
        LocalGet(0),
        LocalGet(6),
        Call(invoke),
        LocalSet(3),
        Br(2),
        End,
        Unreachable,
        End,
        LocalSet(4),
        LocalGet(1),
        I32Const(0),
        RefI31,
        RefEq,
        If(BlockType::Empty),
        LocalGet(4),
        Throw(0),
        End,
        LocalGet(1),
        LocalGet(4),
        ArrayNewFixed {
            array_type_index: ARGS,
            array_size: 1,
        },
        Call(invoke),
        LocalSet(3),
        End,
        Br(2),
        End,
        Unreachable,
        End,
        LocalSet(4),
        I32Const(1),
        LocalSet(5),
        End,
        LocalGet(2),
        I32Const(0),
        RefI31,
        RefEq,
        I32Eqz,
        If(BlockType::Empty),
        LocalGet(2),
        LocalGet(6),
        Call(invoke),
        Drop,
        End,
        LocalGet(5),
        If(BlockType::Empty),
        LocalGet(4),
        Throw(0),
        End,
        LocalGet(3),
    ];
    b.function_with_locals(
        "try-invoke",
        &[VALUE, VALUE, VALUE],
        &[VALUE],
        &[(2, VALUE), (1, ValType::I32), (1, VALUE)],
        &body,
    );
}
