[package]
name = "suss-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
wit-bindgen = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[features]
default = []
component = ["dep:wit-bindgen"]
